---
- name: Configure UFW to allow SSH only
  hosts: all
  become: true
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  tasks:
    - name: Ensure UFW is installed
      apt:
        name: ufw
        state: present
        update_cache: yes

    - name: Allow SSH connections
      ufw:
        rule: allow
        port: 22
        proto: tcp

    - name: Deny all other incoming connections
      ufw:
        rule: deny
        direction: in

    - name: Enable UFW
      ufw:
        state: enabled
        policy: deny
