---
- name: Configure UFW to allow SSH only
  hosts: all
  become: true
  vars:
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  tasks:
    - name: Ensure UFW is installed
      apt:
        name: ufw
        state: present
        update_cache: yes

    - name: Allow SSH connections
      ufw:
        rule: allow
        port: 22
        proto: tcp

    - name: Deny all other incoming connections
      ufw:
        rule: deny
        direction: in

    - name: Enable UFW
      ufw:
        state: enabled
        policy: deny
      
    - name: Backup existing sshd_config
      copy:
        src: /etc/ssh/sshd_config
        dest: /etc/ssh/sshd_config.bak
        backup: yes

    - name: Disable root login
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin no'
        state: present

    - name: Disable password authentication
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication'
        line: 'PasswordAuthentication no'
        state: present

    - name: Restart SSH service to apply changes
      service:
        name: ssh
        state: restarted
